name = "AutomotiveSensors"
uuid = "9ec66b5e-c605-11e8-1454-ede748df6f96"
repo = "https://github.com/sisl/AutomotiveSensors.jl.git"
version = "0.1.3"

[deps]
AutoViz = "82aa6e0c-a491-5edf-8d4b-c16b98e4ea17"
AutomotiveDrivingModels = "99497e54-f3d6-53d3-a3a9-fa9315a7f1ba"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Records = "5984c134-fa48-5ed5-a57f-fc2f6936871f"
Registrator = "4418983a-e44d-11e8-3aec-9789530b3b3e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Vec = "44eeaf0b-fee4-471f-9310-ed6585cb3142"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
