name = "AutomotiveSensors"
uuid = "9ec66b5e-c605-11e8-1454-ede748df6f96"
repo = "https://github.com/sisl/AutomotiveSensors.jl.git"
version = "0.2.0"

[deps]
AutomotiveSimulator = "6aa42d20-6c96-11ea-1103-339224409280"
AutomotiveVisualization = "0faf7fd0-6c98-11ea-1740-03605baa3b07"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
AutomotiveSimulator = "0.1"
AutomotiveVisualization = "0.1"
Distributions = "0.23"
Parameters = "0.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
